# Generated by Django 3.0.2 on 2020-01-29 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_product', models.CharField(db_index=True, max_length=150)),
                ('slug_product', models.SlugField(max_length=150, unique=True)),
                ('description_product', models.TextField(blank=True, db_index=True)),
                ('price_product', models.PositiveIntegerField(blank=True, db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('raiting_product', models.PositiveIntegerField(blank=True, db_index=True, default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
