# Generated by Django 3.0.2 on 2020-01-30 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_product', models.CharField(db_index=True, max_length=150)),
                ('slug_product', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description_product', models.TextField(blank=True, db_index=True)),
                ('price_product', models.PositiveIntegerField(blank=True, db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('raiting_product', models.PositiveIntegerField(blank=True, db_index=True, default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=150)),
                ('first_name', models.CharField(db_index=True, max_length=150)),
                ('last_name', models.CharField(db_index=True, max_length=150)),
                ('password', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('delivery_adress', models.CharField(blank=True, db_index=True, max_length=150)),
            ],
        ),
    ]
