# Generated by Django 3.0.2 on 2020-01-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
