# Generated by Django 3.0.2 on 2020-01-31 14:29

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('eshop_site', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='EShopUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_product', models.PositiveIntegerField(db_index=True, default=0)),
                ('delivery_method', models.CharField(db_index=True, default=None, max_length=150)),
                ('delivery_cost', models.PositiveIntegerField(db_index=True, default=0)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_site.Product')),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_site.EShopUser')),
            ],
        ),
    ]
