# Generated by Django 3.0.2 on 2020-02-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_site', '0004_auto_20200203_1403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_card',
            new_name='Card',
        ),
    ]
