# Generated by Django 3.0.2 on 2020-02-03 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_site', '0005_auto_20200203_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='count',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
