# Generated by Django 3.0.2 on 2020-02-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_site', '0008_card_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
