# Generated by Django 3.0.2 on 2020-02-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_site', '0009_card_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='delivery_method',
            field=models.CharField(db_index=True, default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(db_index=True, default=None, max_length=150),
        ),
    ]
