# Generated by Django 3.0.2 on 2020-02-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_site', '0011_auto_20200205_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='delivery_method',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
