# Generated by Django 3.0.2 on 2020-02-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_site', '0012_auto_20200205_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_title', models.CharField(blank=True, db_index=True, max_length=150)),
                ('id_cat', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
    ]
