# Generated by Django 3.0.2 on 2020-02-05 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_site', '0014_auto_20200205_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categories_title',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='categories',
            name='id_cat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='eshop_site.Categories'),
        ),
    ]
