# Generated by Django 3.0.2 on 2020-02-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_site', '0017_auto_20200205_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arehgaerg',
            field=models.CharField(db_index=True, default=0, max_length=150),
            preserve_default=False,
        ),
    ]
