# Generated by Django 3.0.2 on 2020-02-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_site', '0018_product_arehgaerg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='arehgaerg',
        ),
    ]
